### ISSUE TITLE
MaterialServer listening on wrong interface/IP

### ISSUE THREAD

**Issue by zarmstrong** [CDeenen/MaterialServer#6]
```
Starting Material Server v1.0.2
Websocket on: 169.254.186.61:3001
Stream Deck connected
```

When starting the server, it does not pick up the correct IP (192.168.1.x subnet) and instead uses the self-assigned IP.

**Comment by CDeenen** [comment]
It can in some cases return the wrong IP address if there's multiple network adapters. 
What is your setup like? If Material Server is running on the same computer as the one you use to access Foundry, you should be able to connect to it using localhost:3001. Otherwise you can try connecting using 192.168.1.x if you figure out the local IP of the machine.

**Comment by zarmstrong** [comment]
Ah ok, that was a red herring. Further digging has showed me that it's due to MaterialServer not supporting SSL.

**Comment by CDeenen** [comment]
I'm not sure if this is clear already, but it can still use it if your Foundry server uses SSL:
-Run Material Server locally, so on your computer, the same computer you use to access Foundry (take note that I say 'access', not 'run', because you can run the Foundry server somewhere else)
-Set 'Material Server Address' to 'localhost:3001'

**Comment by zarmstrong** [comment]
Oh duh. I completely brainfarted that this is running via JS in foundry so localhost would indeed work.  Thanks man, that's what happens when I try to get it working at 2am :D
